[HarmonyPatch("TLDModCompatibilityChecker.Name")]
[HarmonyPatch("TLDModCompatibilityChecker.NameType", new Type[] { typeof(int), typeof(string) })]
[HarmonyPatch("TLDModCompatibilityChecker", "NameName")]
[HarmonyPatch("TLDModCompatibilityChecker", "NameNameType", new Type[] { typeof(int), typeof(string) })]
[HarmonyPatch("TLDModCompatibilityChecker", nameof(NameNameOf)]
[HarmonyPatch("TLDModCompatibilityChecker", nameof(NameNameOfType), new Type[] { typeof(int), typeof(string) })]
[HarmonyPatch(nameof(TLDModCompatibilityChecker.NameOf)]
[HarmonyPatch(nameof(TLDModCompatibilityChecker.NameOfType), new Type[] { typeof(int), typeof(string) })]
[HarmonyPatch(nameof(TLDModCompatibilityChecker), "NameOfName")]
[HarmonyPatch(nameof(TLDModCompatibilityChecker), "NameOfNameType", new Type[] { typeof(int), typeof(string) })]
[HarmonyPatch(nameof(TLDModCompatibilityChecker), nameof(NameOfNameOf)]
[HarmonyPatch(nameof(TLDModCompatibilityChecker), nameof(NameOfNameOfType), new Type[] { typeof(int), typeof(string) })]
[HarmonyPatch(typeof(TLDModCompatibilityChecker.TypeOf))]
[HarmonyPatch(typeof(TLDModCompatibilityChecker.TypeOfType), new Type[] { typeof(int), typeof(string) })]
[HarmonyPatch(typeof(TLDModCompatibilityChecker), "TypeOfName")]
[HarmonyPatch(typeof(TLDModCompatibilityChecker), "TypeOfNameType", new Type[] { typeof(int), typeof(string) })]
[HarmonyPatch(typeof(TLDModCompatibilityChecker), nameof(TypeOfNameOf)]
[HarmonyPatch(typeof(TLDModCompatibilityChecker), nameof(TypeOfNameOfType), new Type[] { typeof(int), typeof(string) })]
